# Generated by Django 3.2 on 2022-04-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_product_image',
            field=models.ImageField(blank=True, null=True, upload_to='main_product_image'),
        ),
    ]
