# Generated by Django 3.2 on 2022-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='description',
        ),
        migrations.AddField(
            model_name='setting',
            name='decription',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
