# Generated by Django 3.2 on 2022-03-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20220329_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='decription',
            new_name='description',
        ),
    ]
